# Analysis Configuration
# Project settings and data paths for reproducible analysis

# Paths configuration  
paths:
  # Raw data path (update this to your data location)
  TFT: /Users/JoshsMacbook2015/Library/CloudStorage/OneDrive-EmoryUniversity/Research/MS_raw_data/Chan_studies_MS_raw/PGD studies/Chan_PGD_9_2025/MetaboJanitoR/Outputs/MSMICA/global_KEGG/MSMICA_Feature_Tables/MSMICA_20p_halfmin_log2.csv
  UFT_full: /Users/JoshsMacbook2015/Library/CloudStorage/OneDrive-EmoryUniversity/Research/MS_raw_data/Chan_studies_MS_raw/PGD studies/Chan_PGD_9_2025/MetaboJanitoR/Outputs/Simple/UFT_full_halfmin_log2.csv
  UFT_filtered: /Users/JoshsMacbook2015/Library/CloudStorage/OneDrive-EmoryUniversity/Research/MS_raw_data/Chan_studies_MS_raw/PGD studies/Chan_PGD_9_2025/MetaboJanitoR/Outputs/Untargeted/UFT_20p_halfmin_log2.csv
  clinical_metadata: "/Users/JoshsMacbook2015/Library/CloudStorage/OneDrive-EmoryUniversity/Research/Chan Lab - Transplant Multi-Omics - OHT/OHT Clinical Data Master Sheet.xlsx"
  # Output paths (relative to project root)
  output: "./Outputs"
  
  # Script and utility paths
  scripts: "R/Scripts/"
  utils: "R/Utilities/"

# Analysis settings
analysis:
  # Project metadata
  project_name: "Postop_PGD_9_2024"
  description: "PGD Preop Metabolomics Analysis"
  
  # Environment preferences
  tibble_options:
    print_max: 20
    print_min: 10
    sigfig: 3
    
  # Data.table preferences  
  datatable_options:
    print_class: true
    print_keys: true
    aware: true
