# Alternative Simple Configuration
# Just set COMPUTER="laptop" or COMPUTER="desktop" as environment variable

# Analysis Configuration - Environment Variable Approach
paths:
  # Raw data paths - uses environment variable substitution
  TFT: "${DATA_ROOT}/MetaboJanitoR${METABO_SUFFIX}/Outputs/MSMICA/global_KEGG/MSMICA_Feature_Tables/MSMICA_20p_halfmin_log2.csv"
  TFT_key: "${DATA_ROOT}/MetaboJanitoR${METABO_SUFFIX}/Outputs/MSMICA/global_KEGG/MSMICA_Feature_Tables/MSMICA_feature_key.csv"
  UFT_full: "${DATA_ROOT}/MetaboJanitoR${METABO_SUFFIX}/Outputs/Untargeted/UFT_full_halfmin_log2.csv"  
  UFT_filtered: "${DATA_ROOT}/MetaboJanitoR${METABO_SUFFIX}/Outputs/Untargeted/UFT_20p_halfmin_log2.csv"
  clinical_metadata: "${ONEDRIVE_ROOT}/Research/Chan Lab - Transplant Multi-Omics - OHT/OHT Clinical Data Master Sheet.xlsx"
  sample_type: "${DATA_ROOT}/sample_type.xlsx"
  
  # Local paths (same across computers)
  qstd_c18: "Databases/IDX_IROA/Qstd4_IROA_C18neg_quantification_HFQE_Fusion_09252025.txt"
  qstd_hilic: "Databases/IDX_IROA/Qstd4_IROA_HILICpos_quantification_HFQE_Fusion_09252025.txt"
  idx_library: "Databases/IDX_IROA/IDX_lib.csv"
  
  # Output paths
  output: "./Outputs"
  figures: "${FIGURES_PATH}"
  scripts: "R/Scripts/"
  utils: "R/Utilities/"

# Rest of config stays the same...
analysis:
  project_name: "Postop_PGD_9_2024"
  description: "PGD Preop Metabolomics Analysis"
  # ... (rest unchanged)