#' Read Mummichog JSON Results File
#'
#' Parses a Mummichog JSON output file and extracts pathway enrichment results
#' into a standardized tibble format.
#'
#' @param file_path Character string specifying the path to the Mummichog JSON file
#'
#' @return A tibble with columns:
#'   - pathway: Pathway names
#'   - enrichment: Enrichment scores
#'   - p_value: Statistical p-values for pathway enrichment
#'
#' @details
#' This function reads JSON files generated by Mummichog pathway enrichment analysis
#' and extracts the key results (pathway names, enrichment scores, and p-values)
#' into a clean tibble format for downstream analysis and visualization.
#'
#' @examples
#' \dontrun{
#'   # Read Mummichog results
#'   results <- read_mummichog_json("path/to/mummichog_results.json")
#'   
#'   # View top enriched pathways
#'   results %>% arrange(p_value) %>% head(10)
#' }
#'
#' @importFrom jsonlite fromJSON
#' @importFrom tibble tibble
#' @export
read_mummichog_json <- function(file_path) {
  dat <- fromJSON(file_path)
  tibble(
    pathway = dat$pathnames,
    enrichment = dat$enr,
    p_value = dat$pval
  )
}
