---
output:
  pdf_document:
    latex_engine: xelatex
bibliography: "../References/Supporting_AJT.bib"
csl: "../References/jama.csl"
header-includes:
  - \usepackage{fontspec}
  - \setmainfont{Arial}
  - \hyphenpenalty=10000
  - \exhyphenpenalty=10000
---

\begin{center}
\textit{\Large Supporting Information for:}
\end{center}

\begin{center}
\textbf{\Large Recipient Plasma Metabolomics as a Predictor of Heart Transplant Severe Primary Graft Dysfunction}
\end{center}

\vspace{1em}

Joshua D. Preston, BS^1,2^, Clayton J. Rust, MD^1^, Aubrey C. Reed, BS^1^, Supreet S. Randhawa, MS^1^, Ailin Tang, BS^1^, Kimberly A. Rooney, BS^3^, Misho Kozmava, BS^3^, Jaclyn Weinberg, BS^2^, Lucy Avant, BS^1^, Catherine L.B. McGeoch, MD, MSc^1^, Gustavo A. Parrilla, MD^1^, Jiada Zhan, BS, RD^2^, Michael E. Halkos, MD, MSc^1^, Muath M. Bishawi, MD PhD^1^, Mani A. Daneshmand, MD^1^, Arshed A. Quyyumi, MD^3^, Charles D. Searles, MD^3^, Young-Mi Go, PhD^2^, Dean P. Jones, PhD^2^, Joshua L. Chan, MD^1^

\vspace{1em}

^1^Division of Cardiothoracic Surgery, Department of Surgery, Emory University School of Medicine, Atlanta, GA, USA

^2^Division of Pulmonary, Allergy, Critical Care, and Sleep Medicine, Department of Medicine, Emory University School of Medicine, Atlanta, GA, USA

^3^Division of Cardiology, Department of Medicine, Emory University School of Medicine, Atlanta, GA, USA

\vspace{2em}

\begin{center}
\textbf{\large Table of Contents}
\end{center}

\vspace{1em}

**Supplemental Figure 1** ........................................................................................ 2

**Supplemental Figure 2** ........................................................................................ 3
\hspace{1em} Supplemental Figure 2.1 ..................................................................... 3
\hspace{1em} Supplemental Figure 2.2 ..................................................................... 3
\hspace{1em} Supplemental Figure 2.3 ..................................................................... 3
\hspace{1em} Supplemental Figure 2.4 ..................................................................... 3
\hspace{1em} Supplemental Figure 2.5 ..................................................................... 3

**Expanded Metabolomics Methods and Other Technical Details** ................................. 4
\hspace{1em} Sample Collection and Processing ...................................................... 4
\hspace{1em} Metabolomics Profiling with Liquid Chromatography-Mass Spectrometry (LC-MS) ... 4
\hspace{1em} Feature Extraction, Annotation, and Identification ................................. 4
\hspace{1em} Data Structuring and Transformation ................................................ 4

**References** ....................................................................................................... 5

\newpage